import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import {
  ThemeContext,
  ThemeController,
  ThemeProvider,
} from "./components/ThemeController/ThemeController";
import AppProvider from "./components/ThemeController/AppController";

const axiformaRegular = localFont({
  src: [
    {
      path: "./fonts/axiforma-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/axiforma-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/axiforma-semi-bold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-axiforma",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${axiformaRegular.className} antialiased`}>
        <AppProvider>
          <ThemeProvider>
            <ThemeController>
              <Navbar />
              {children}
            </ThemeController>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
